<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Naravel.Cache.Memcached</PackageId>
    <Description>Memcached cache and lock providers for Naravel.Cache.</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Naravel.Cache\Naravel.Cache.csproj" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="EnyimMemcachedCore" />
    <PackageReference Include="MessagePack" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>
</Project>
