using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Primitives;
using System.Net.Http.Headers;

namespace Naravel.Routing;

/// <summary>Controls the process-local HTTP maintenance state.</summary>
/// <remarks>
/// <para><b>Laravel equivalent:</b> maintenance mode request gating.</para>
/// <para><b>Why it exists:</b> a small route-level switch with a bypass secret and retry hint.</para>
/// <para><b>Not ported:</b> distributed state, generated bypass URLs, and Console commands.</para>
/// </remarks>
public sealed class MaintenanceModeService
{
    internal sealed record State(bool Enabled, string? BypassSecret, TimeSpan RetryAfter);

    private State _state = new(false, null, TimeSpan.FromSeconds(60));

    /// <summary>Whether maintenance mode is enabled in this process.</summary>
    public bool IsEnabled => Volatile.Read(ref _state).Enabled;

    /// <summary>Enables maintenance mode, optionally allowing a request with the matching bypass header.</summary>
    public void Enable(string? bypassSecret = null, TimeSpan? retryAfter = null)
    {
        var delay = retryAfter ?? TimeSpan.FromSeconds(60);
        ArgumentOutOfRangeException.ThrowIfLessThanOrEqual(delay, TimeSpan.Zero);
        Volatile.Write(ref _state, new State(true, string.IsNullOrWhiteSpace(bypassSecret) ? null : bypassSecret, delay));
    }

    /// <summary>Disables maintenance mode.</summary>
    public void Disable() => Volatile.Write(ref _state, new State(false, null, TimeSpan.FromSeconds(60)));

    internal State Current => Volatile.Read(ref _state);

    internal bool IsBypassed(HttpContext context, State state)
    {
        var supplied = context.Request.Headers["X-Naravel-Maintenance-Bypass"].ToString();
        if (state.BypassSecret is null || supplied.Length == 0) return false;
        return CryptographicOperations.FixedTimeEquals(Encoding.UTF8.GetBytes(supplied), Encoding.UTF8.GetBytes(state.BypassSecret));
    }
}

internal sealed class MaintenanceMiddleware(MaintenanceModeService maintenance) : IRouteMiddleware
{
    public async Task InvokeAsync(HttpContext context, RequestDelegate next, MiddlewareArguments arguments)
    {
        var state = maintenance.Current;
        if (!state.Enabled || maintenance.IsBypassed(context, state))
        {
            await next(context).ConfigureAwait(false);
            return;
        }

        context.Response.StatusCode = StatusCodes.Status503ServiceUnavailable;
        context.Response.Headers.RetryAfter = Math.Max(1, (long)Math.Ceiling(state.RetryAfter.TotalSeconds))
            .ToString(CultureInfo.InvariantCulture);
    }
}

internal sealed class CacheHeadersMiddleware : IRouteMiddleware
{
    public async Task InvokeAsync(HttpContext context, RequestDelegate next, MiddlewareArguments arguments)
    {
        if (arguments.Count == 0) throw new InvalidOperationException("cache.headers requires one or more Cache-Control directives.");
        var value = CacheControlHeaderValue.Parse(string.Join(", ", arguments)).ToString();
        context.Response.OnStarting(static state =>
        {
            var (response, cacheControl) = ((HttpResponse, string))state;
            response.Headers.CacheControl = cacheControl;
            return Task.CompletedTask;
        }, (context.Response, value));
        await next(context).ConfigureAwait(false);
    }
}

internal sealed class TrimStringsMiddleware : InputNormalizationMiddleware
{
    protected override bool Trim => true;
    protected override bool ConvertEmptyToNull => false;
}

internal sealed class ConvertEmptyStringsToNullMiddleware : InputNormalizationMiddleware
{
    protected override bool Trim => false;
    protected override bool ConvertEmptyToNull => true;
}

internal abstract class InputNormalizationMiddleware : IRouteMiddleware
{
    protected abstract bool Trim { get; }
    protected abstract bool ConvertEmptyToNull { get; }

    public async Task InvokeAsync(HttpContext context, RequestDelegate next, MiddlewareArguments arguments)
    {
        context.Request.Query = new QueryCollection(Normalize(context.Request.Query));
        if (context.Request.HasFormContentType)
        {
            var form = await context.Request.ReadFormAsync(context.RequestAborted).ConfigureAwait(false);
            context.Request.Form = new FormCollection(Normalize(form), form.Files);
        }

        await next(context).ConfigureAwait(false);
    }

    private Dictionary<string, StringValues> Normalize(IEnumerable<KeyValuePair<string, StringValues>> source)
    {
        var result = new Dictionary<string, StringValues>(StringComparer.OrdinalIgnoreCase);
        foreach (var (key, values) in source)
        {
            var normalized = new string?[values.Count];
            for (var index = 0; index < values.Count; index++)
            {
                var value = values[index];
                if (value is not null && Trim) value = value.Trim();
                if (value is { Length: 0 } && ConvertEmptyToNull) value = null;
                normalized[index] = value;
            }

            result[key] = new StringValues(normalized);
        }

        return result;
    }
}

internal sealed class GuestMiddleware : IRouteMiddleware
{
    public Task InvokeAsync(HttpContext context, RequestDelegate next, MiddlewareArguments arguments)
    {
        if (context.User.Identity?.IsAuthenticated == true)
        {
            context.Response.StatusCode = StatusCodes.Status403Forbidden;
            return Task.CompletedTask;
        }

        return next(context);
    }
}