<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="EnyimMemcachedCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Naravel.Cache\Naravel.Cache.csproj" />
    <ProjectReference Include="..\..\src\Naravel.Cache.Redis\Naravel.Cache.Redis.csproj" />
    <ProjectReference Include="..\..\src\Naravel.Cache.Memcached\Naravel.Cache.Memcached.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="FluentAssertions" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Shared\ServiceFactAttribute.cs" Link="ServiceFactAttribute.cs" />
  </ItemGroup>
</Project>
